person:
  id: 2
  name: qi
  hobby:
    - play
    - read
    - sleep
  family: [ father,mother ]
  map: { k1: v1, k2: v2 }
  pet: { type cat,name: tom}

student:
  name: name
  id: 001

spring:
  profiles:
    active: dev

